development:
  adapter: postgresql
  encoding: unicode
  database: infomercialipsum_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: infomercialipsum_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: infomercialipsum_production
  pool: 5
